
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Tmpl
{
public partial class Tables
{
    public TbUIParam TbUIParam {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbUIParam = new TbUIParam(loader("tbuiparam"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbUIParam.ResolveRef(this);
    }
}

}
