
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Tmpl
{
public partial class TbUIParam
{
    private readonly System.Collections.Generic.Dictionary<string, UIParam> _dataMap;
    private readonly System.Collections.Generic.List<UIParam> _dataList;
    
    public TbUIParam(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, UIParam>();
        _dataList = new System.Collections.Generic.List<UIParam>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIParam _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = UIParam.DeserializeUIParam(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.DialogName, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, UIParam> DataMap => _dataMap;
    public System.Collections.Generic.List<UIParam> DataList => _dataList;

    public UIParam GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UIParam Get(string key) => _dataMap[key];
    public UIParam this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

