
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Tmpl.UI
{ 
    public enum Mode
    {
        None = 0,
        /// <summary>
        /// 全屏栈窗口
        /// </summary>
        Stack = 1,
        /// <summary>
        /// 弹出式子窗口
        /// </summary>
        Popup = 2,
        /// <summary>
        /// 模态弹出框
        /// </summary>
        Modal = 3,
        /// <summary>
        /// 顶层窗口(如Loading)
        /// </summary>
        TopMost = 4,
        Max = 5,
    }

} 

