
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace Tmpl
{
public sealed partial class UIParam : Luban.BeanBase
{
    public UIParam(JSONNode _buf) 
    {
        { if(!_buf["dialog_name"].IsString) { throw new SerializationException(); }  DialogName = _buf["dialog_name"]; }
        { if(!_buf["package_name"].IsString) { throw new SerializationException(); }  PackageName = _buf["package_name"]; }
        { if(!_buf["component_name"].IsString) { throw new SerializationException(); }  ComponentName = _buf["component_name"]; }
        { var __json0 = _buf["dependency_packages"]; if(!__json0.IsArray) { throw new SerializationException(); } DependencyPackages = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  DependencyPackages.Add(__v0); }   }
        { if(!_buf["layer"].IsNumber) { throw new SerializationException(); }  Layer = (UI.Mode)_buf["layer"].AsInt; }
        { if(!_buf["isFull"].IsBoolean) { throw new SerializationException(); }  IsFull = _buf["isFull"]; }
        { if(!_buf["isBlur"].IsBoolean) { throw new SerializationException(); }  IsBlur = _buf["isBlur"]; }
    }

    public static UIParam DeserializeUIParam(JSONNode _buf)
    {
        return new UIParam(_buf);
    }

    /// <summary>
    /// 界面类名
    /// </summary>
    public readonly string DialogName;
    /// <summary>
    /// 包名
    /// </summary>
    public readonly string PackageName;
    /// <summary>
    /// 组件名
    /// </summary>
    public readonly string ComponentName;
    /// <summary>
    /// 依赖的其他包名
    /// </summary>
    public readonly System.Collections.Generic.List<string> DependencyPackages;
    /// <summary>
    /// 层级
    /// </summary>
    public readonly UI.Mode Layer;
    /// <summary>
    /// 是否全屏
    /// </summary>
    public readonly bool IsFull;
    /// <summary>
    /// 是否背景模糊
    /// </summary>
    public readonly bool IsBlur;
   
    public const int __ID__ = 295213657;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "dialogName:" + DialogName + ","
        + "packageName:" + PackageName + ","
        + "componentName:" + ComponentName + ","
        + "dependencyPackages:" + Luban.StringUtil.CollectionToString(DependencyPackages) + ","
        + "layer:" + Layer + ","
        + "isFull:" + IsFull + ","
        + "isBlur:" + IsBlur + ","
        + "}";
    }
}

}
